export const dialogFormTypes = {
  UPDATE_EXPENSE_SUB_CATEGORY_DIALOG: 'UPDATE_EXPENSE_SUB_CATEGORY_DIALOG',
  ADD_EXPENSE_SUB_CATEGORY_DIALOG: 'ADD_EXPENSE_SUB_CATEGORY_DIALOG',
  DELETE_EXPENSE_SUB_CATEGORY_DIALOG: 'DELETE_EXPENSE_SUB_CATEGORY_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
};
