export const dialogFormTypes = {
  DELETE_BUDGET_DIALOG: 'DELETE_BUDGET_DIALOG',
  UPDATE_EXPENSE_SUB_CATEGORY_DIALOG: 'UPDATE_EXPENSE_SUB_CATEGORY_DIALOG',
  ADD_EXPENSE_SUB_CATEGORY_DIALOG: 'ADD_EXPENSE_SUB_CATEGORY_DIALOG',
  DELETE_EXPENSE_SUB_CATEGORY_DIALOG: 'DELETE_EXPENSE_SUB_CATEGORY_DIALOG',
  UPDATE_INCOME_CATEGORY_DIALOG: 'UPDATE_INCOME_CATEGORY_DIALOG',
  DELETE_INCOME_CATEGORY_DIALOG: 'DELETE_INCOME_CATEGORY_DIALOG',
  UPDATE_EXPENSE_CATEGORY_DIALOG: 'UPDATE_EXPENSE_CATEGORY_DIALOG',
  DELETE_EXPENSE_CATEGORY_DIALOG: 'DELETE_EXPENSE_CATEGORY_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
};
