export const budgetTypes = {
  CREATE_BUDGET: 'CREATE_BUDGET',
  CREATE_BUDGET_REQUEST: 'CREATE_BUDGET_REQUEST',
  ADD_REVENUE_CATEGORY: 'ADD_REVENUE_CATEGORY',
  DELETE_REVENUE_CATEGORY: 'DELETE_REVENUE_CATEGORY',
  ADD_EXPENSE_CATEGORY: 'ADD_EXPENSE_CATEGORY',
  DELETE_EXPENSE_CATEGORY: 'DELETE_EXPENSE_CATEGORY',
};
