export const budgetTypes = {
  CREATE_BUDGET: 'CREATE_BUDGET',
  CREATE_BUDGET_REQUEST: 'CREATE_BUDGET_REQUEST',
  GET_ALL_BUDGET: 'GET_ALL_BUDGET',
  GET_BUDGET: 'GET_BUDGET',
  SELECTED_BUDGET: 'SELECTED_BUDGET',
  ADD_REVENUE_CATEGORY: 'ADD_REVENUE_CATEGORY',
  DELETE_REVENUE_CATEGORY: 'DELETE_REVENUE_CATEGORY',
  ADD_EXPENSE_CATEGORY: 'ADD_EXPENSE_CATEGORY',
  DELETE_EXPENSE_CATEGORY: 'DELETE_EXPENSE_CATEGORY',
  DELETE_EXPENSE_SUB_CATEGORY: 'DELETE_EXPENSE_SUB_CATEGORY',
};
